name: Deploy to Render

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BE to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BACKEND_KEY }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Deploy FE to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FRONTEND_KEY }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true